---
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: XChem Knitwork Tools
collection: knitwork

jobs:
  knitwork:
    name: Fragments molecules in an SDF
    description: >-
      The Fragment process looks for subnodes and synthons for a given set of
      fragments/molecules in an SDF and groups them into pairs.
    version: '1.0.0'
    category: knitwork
    image:
      name: xchem/knitwork
      tag: latest
      project-directory: /app/data
      working-directory: /app
      # fix-permissions: true # requires outputs
      environment:
      - name: NEO4J_USERNAME
        value-from:
          secret:
            name: im-fragnet-graph
            key: username
      - name: NEO4J_PASSWORD
        value-from:
          secret:
            name: im-fragnet-graph
            key: password
      # The location
      # Something like 'neo4j://localhost:7687'
      - name: NEO4J_LOCATION
        value-from:
          secret:
            name: im-fragnet-graph
            key: server
    command: >-
      /bin/bash ./run_knitwork.sh {{ DM_INSTANCE_DIRECTORY }}
