---

name: Publish release image

# ---------------
# Control secrets
# ---------------
#
# At the GitHub 'organisation' or 'project' level you are expected to
# have the following GitHub 'Repository Secrets' defined
# (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME      required
# DOCKERHUB_TOKEN         required
#
# Unlike the 'latest' workflow the credentials are not optional here,
# a release that fails to publish its image should fail loudly.
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# (none)

on:
  push:
    # Semantic version tags (with no 'v' prefix), i.e. '1.0.0' or '1.0.0-rc.1'.
    # The image is published using the same tag.
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Check out the repo
      uses: actions/checkout@v5
    - name: Set lower case owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >>"${GITHUB_ENV}"
      env:
        OWNER: '${{ github.repository_owner }}'
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ env.OWNER_LC }}/knitwork:${{ github.ref_name }}
        push: true
